### ISSUE TITLE
about lib aw-matlib

### ISSUE THREAD

**Issue by riyueshi** [adasworks/ocamcalib-plus#1]
Hi,
 I am trying to build the project and the ocamcalib project need "aw-matlib" but I can't get any information about that lib. could you please provide a download link? 
Miller Zhang

**Comment by tamaskenez** [comment]
Hi,

The `aw-matlib` is an internal library of our company and for now it's not public. But it's not a big deal, because you don't really need it on order to do C++ calibration:

- The `cpp` project contains two projects: `CameraCalibration` (main project), which is the actual C++ port of the MatLab toolbox, and `OcamDistort` (`distort` subdir) which is only a test for undistortion.

You can leave out the `distort` subdir. I've just uploaded a commit which automatically leaves out the `distort` subdir if there's no `aw-matlib`.

If you do need the stuff in `distort` feel free to convert the `aw-matlib` calls to some other library (like Eigen3) and send us a PR. It's just basic matrix operations.

**Comment by riyueshi** [comment]
I had build the project successfully without the distort function (actually I don't need that function), and it works well. thanks a lot for sharing this code : )
(English is not my native language, just for curious, what does the "PR" means in "send us a PR")

**Comment by tamaskenez** [comment]
Okay, you're welcome.
PR is for pull request.
